spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/logtracker
    username: logtracker_be
    password: sujeong88*
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

server:
  port: 8888

openai:
  api-key: ${OPENAI_API_KEY}
  chat-model: gpt-4.1-mini
  embedding-model: text-embedding-3-small

pinecone:
  api-key: ${PINECONE_API_KEY}
  index-name: ${PINECONE_INDEX_NAME:logtracker-issues}
